name = "JavaScript"
language = "javascript"
status = "beta"
features = ["ast","uast","roles"]

[documentation]
description  = """
JavaScript driver for [babelfish](https://github.com/bblfsh/bblfshd).
"""

[runtime]
os = "alpine"
go_version = "1.9"
native_version = ["8.9.3-r1"]
